//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMatricula.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class clinicaEntities : DbContext
    {
        public clinicaEntities()
            : base("name=clinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Medicos> Medicos { get; set; }
        public virtual DbSet<tabesp> tabesp { get; set; }
    
        public virtual int spCita(string codmed, string nompac, Nullable<int> tipo, Nullable<decimal> pago)
        {
            var codmedParameter = codmed != null ?
                new ObjectParameter("codmed", codmed) :
                new ObjectParameter("codmed", typeof(string));
    
            var nompacParameter = nompac != null ?
                new ObjectParameter("nompac", nompac) :
                new ObjectParameter("nompac", typeof(string));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var pagoParameter = pago.HasValue ?
                new ObjectParameter("pago", pago) :
                new ObjectParameter("pago", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCita", codmedParameter, nompacParameter, tipoParameter, pagoParameter);
        }
    }
}
